Hotel_Management_System/Models/Issuebill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace Hotel_Management_System.Models
{
    public class Issuebill
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int IssueBillId { get; set; }

        [DataMember]

        public int RoomNo { get; set; }

        [DataMember]

        public int BillNo { get; set; }
        [DataMember]

        public int Quantity { get; set; }
        [DataMember]

        public double Price { get; set; }
        [DataMember]

        public double Taxes { get; set; }
        [DataMember]

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }
        [DataMember]
        public double Services { get; set; }

        public double Total { get; set; }
    }
}

Hotel_Management_System/Controllers/IssuebillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_Management_System.Models;
using Rotativa;

namespace Hotel_Management_System.Controllers
{
    public class IssuebillsController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Issuebills
        public ActionResult Index()
        {
            return View(db.Issuebill.ToList());
        }

        //print docs

        public ActionResult GetAll()
        {
            var allprint=db.Issuebill.ToList();
            return View(allprint);
        }
        public ActionResult PrintAll()
        {
            var q = new ActionAsPdf("GetAll");
            return q;
        }



        public ActionResult addbill()
        {
            return View(new Issuebill());
        }
        //isuue bill
        [HttpPost]
        public ActionResult addbill(Issuebill i, string calculate)
        {
                i.Taxes = 0.18;
                i.Total = ((i.Price * i.Quantity)+i.Services)+i.Taxes;
               
                db.Issuebill.Add(i);
                db.SaveChanges();
            return View(i);

        }

        // GET: Issuebills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Issuebill issuebill = db.Issuebill.Find(id);
            if (issuebill == null)
            {
                return HttpNotFound();
            }
            return View(issuebill);
        }

        // GET: Issuebills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Issuebills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IssueBillId,RoomNo,BillNo,Quantity,Price,Taxes,Date,Services,Total")] Issuebill issuebill)
        {
            if (ModelState.IsValid)
            {
                db.Issuebill.Add(issuebill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(issuebill);
        }

        // GET: Issuebills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Issuebill issuebill = db.Issuebill.Find(id);
            if (issuebill == null)
            {
                return HttpNotFound();
            }
            return View(issuebill);
        }

        // POST: Issuebills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IssueBillId,RoomNo,BillNo,Quantity,Price,Taxes,Date,Services,Total")] Issuebill issuebill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(issuebill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(issuebill);
        }

        // GET: Issuebills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Issuebill issuebill = db.Issuebill.Find(id);
            if (issuebill == null)
            {
                return HttpNotFound();
            }
            return View(issuebill);
        }

        // POST: Issuebills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Issuebill issuebill = db.Issuebill.Find(id);
            db.Issuebill.Remove(issuebill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel_Management_System/Views/Issuebills/Create.cshtml
@model Hotel_Management_System.Models.Issuebill

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>










<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Issuebill</h4>
        <hr />
        <h3>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Taxes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Taxes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Taxes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Services, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Services, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Services, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                </div>
            </div>
        </h3>

        <button type="submit" class="btn-btn-info" id="add" value="add">calculate</button>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="submit" value="Create" class="btn btn-default" />*@
                <input type="submit" value="Create" class="btn btn-default" onclick="return click_here_to_save();" />
                <script type="text/javascript">function click_here_to_save() { alert('Data Created successfully '); }</script>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_Management_System/Views/Issuebills/Delete.cshtml
@model Hotel_Management_System.Models.Issuebill

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>








<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Issuebill</h4>
    <hr />
    <h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RoomNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RoomNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BillNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BillNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Taxes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Taxes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Services)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Services)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Total)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Total)
            </dd>

        </dl>
    </h3>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @*  <input type="submit" value="Delete" class="btn btn-default" /> |*@
            <input type="submit" value="Delete" class="btn btn-default" onclick="return click_here_to_save();" />
            <script type="text/javascript">function click_here_to_save() { alert('Data Deleted successfully '); }</script>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel_Management_System/Views/Issuebills/Details.cshtml
@model Hotel_Management_System.Models.Issuebill

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>










<h2>Details</h2>

<div>
    <h4>Issuebill</h4>
    <hr />
    <h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.RoomNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RoomNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BillNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BillNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Taxes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Taxes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Services)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Services)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Total)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Total)
            </dd>

        </dl>
    </h3>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IssueBillId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel_Management_System/Views/Issuebills/Edit.cshtml
@model Hotel_Management_System.Models.Issuebill

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>









<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Issuebill</h4>
        <hr />
        <h3>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.IssueBillId)

            <div class="form-group">
                @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Taxes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Taxes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Taxes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Services, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Services, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Services, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                </div>
            </div>
        </h3>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="submit" value="Save" class="btn btn-default" />*@
                <input type="submit" value="Save" class="btn btn-default" onclick="return click_here_to_save();" />
                <script type="text/javascript">function click_here_to_save() { alert('Data Edited successfully '); }</script>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_Management_System/Views/Issuebills/GetAll.cshtml
@model IEnumerable<Hotel_Management_System.Models.Issuebill>

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>



<h2>GetAll</h2>

<p>
    @Html.ActionLink("Print", "PrintAll")
</p>
<h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Taxes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Services)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BillNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Taxes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Services)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.IssueBillId }) |
                        @Html.ActionLink("Details", "Details", new { id=item.IssueBillId }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.IssueBillId })
                    </td>*@
            </tr>
        }

    </table>
</h4>

Hotel_Management_System/Views/Issuebills/Index.cshtml
@model IEnumerable<Hotel_Management_System.Models.Issuebill>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>

</head>



<h2>IssueBill</h2>

<p>
    @Html.ActionLink("Create New", "addbill")
</p>
<h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Taxes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Services)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoomNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BillNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Taxes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Services)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IssueBillId }) |
            @Html.ActionLink("Details", "Details", new { id = item.IssueBillId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IssueBillId })|
            <button><a href="https://localhost:44376/Issuebills/GetAll">PrintDoc</a></button>
        </td>
        <button><a href="https://localhost:44376/Payments">Payments</a></button>
    </tr>
        }

    </table>
</h4>

Hotel_Management_System/Views/Issuebills/addbill.cshtml
@model Hotel_Management_System.Models.Issuebill

@{
    ViewBag.Title = "addbill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html>
<head>
    <style>
        .logo-w3 {
            position: relative;
            font-family: Arial;
        }

        .text-block {
            position: absolute;
            bottom: 20px;
            right: 20px;
            background-color: blanchedalmond;
            color: white;
            padding-left: 20px;
            padding-right: 20px;
        }



        body {
            background-repeat: no-repeat;
            background-image: url('../../Images/issuebills.png');
            background-attachment: fixed;
            background-size: cover;
        }
    </style>



</head>












<h2>Create</h2>

<html>
<head>
    <body>
        <h2> Add Bills  </h2>
        <h3>
            <div class="row">
                @using (Html.BeginForm("/addbill", "Issuebills", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="RoomNo">Room No</label>
                        <input type="text" class="form-control" id="RoomNo" name="RoomNo" value="@Model.RoomNo" />
                    </div>

                    <div class="form-group">
                        <label for="BillNo">Bill No </label>
                        <input type="text" class="form-control" id="BillNo" name="BillNo" value="@Model.BillNo" />
                    </div>

                    <div class="form-group">
                        <label for="Quantity">Quantity</label>
                        <input type="text" class="form-control" id="Quantity" name="Quantity" value="@Model.Quantity" />
                    </div>

                    <div class="form-group">
                        <label for="Price">Price</label>
                        <input type="text" class="form-control" id="Price" name="Price" value="@Model.Price" />
                    </div>

                    <div class="form-group">
                        <label for="Taxes">Taxes</label>
                        <input type="text" class="form-control" id="Taxes" name="Taxes" value="@Model.Taxes" />
                    </div>

                    <div class="form-group">
                        <label for="Date">Date</label>
                        <input type="datetime-local" class="form-control" id="Date" name="Date" value="@Model.Date" />
                    </div>

                    <div class="form-group">
                        <label for="Services">Services</label>
                        <input type="text" class="form-control" id="Services" name="Services" value="@Model.Services" />
                    </div>


                    <div class="form-group">
                        <label for="Total">Total</label>
                        <input type="text" class="form-control" id="Total" name="Total" value="@Model.Total" />
                    </div>

                    @* <button type="submit" class="btn-btn-info" id="add" value="add">calculate</button>*@
                    <input type="submit" value="Create" class="btn btn-default" onclick="return click_here_to_save();" />
                    <script type="text/javascript">function click_here_to_save() { alert('Data Created successfully '); }</script>
                }
            </div>
        </h3>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

    </body>
</head>
</html>